### ISSUE TITLE
@require inside modules not working 

### ISSUE THREAD

**Issue by shashi** [JuliaPackaging/Requires.jl#11]
(with Julia 0.4)

``` julia
julia> module X
          using Requires; @require Lazy println("Loading Lazy")
       end
X

julia> using Lazy
```

(prints nothing)

If I put the `@require` in the top level, it works as expected.

`modlisteners` does contain an entry for "Lazy" in either case.

**Comment by shashi** [comment]
@one-more-minute any ideas what is going on here? I'm happy to make a PR for this but I cannot figure out what's up. The hacking game in this package is too damn strong :)

**Comment by shashi** [comment]
if there is a `using Requires` at the top level, it seems to work fine,
```julia
julia> using Requires

julia> module X
       using Requires
       @require Lazy println("foo")
       end
X

julia> using Lazy
foo
```
but not quite:

```julia
julia> using Requires

julia> module X
       using Requires; @require Compose println("Foo")
       @require Gadfly println("Bar")
       end
X

julia> using Gadfly
Bar

```
(notice it didn't print `Foo` as well)

**Comment by ianfiske** [comment]
Is this still an issue?  I am developing a package and seem to be hitting this issue.  However, I've seen the same usage in @tbreloff 's Plots.jl extensively and it seems to work there.  I've studied the code in Plots.jl but can't seem to find the magic that let's it work there, but not for me.  I'm on Julia 0.6.  Any ideas?

**Comment by timholy** [comment]
This should work fine now. You need to put the `@require` inside the sub-modules' `__init__` function.
