### ISSUE TITLE
New home for @require_extensions?

### ISSUE THREAD

**Issue by cjdoris** [JuliaPackaging/Requires.jl#114]
C.f. cjdoris/PackageExtensionTools.jl#1, I have a macro `@require_extensions` which is a no-op on Julia 1.9 but uses `@require` to load package extensions on earlier versions of Julia. This provides some backwards-compatibility for package extensions.

It seems to me that Requires.jl is a good home for this macro. I can make a PR to move it here if you like?

**Comment by vchuravy** [comment]
I would be okay with that.

cc: @timholy @KristofferC

**Comment by cjdoris** [comment]
I've decided this is better in its own package, because then it can avoid loading Requires.jl at all on v1.9+.
