### ISSUE TITLE
LoadError: MethodError: objects of type LambdaInfo are not callable

### ISSUE THREAD

**Issue by ashleylid** [JuliaPackaging/Requires.jl#23]
Julia Version 0.5.0-dev+3438 (2016-04-07 15:46 UTC). 14.04.1-Ubuntu SMP Wed Apr 6 22:56:34 UTC 201
I think this error has to do with Requires because of the lines following it: 
### 

LoadError: MethodError: objects of type LambdaInfo are not callable
 [inlined code] from /home/ashley/.julia/v0.5/Requires/src/require.jl:11
 in require(::Symbol) at /home/ashley/.julia/v0.5/Requires/src/hook.jl:17
 in include(::ASCIIString) at ./boot.jl:234
 in include_from_node1(::UTF8String) at ./loading.jl:417
 in process_options(::Base.JLOptions) at ./client.jl:262
 in _start() at ./client.jl:318
###

**Comment by MikeInnes** [comment]
For now, you can check out Requires master to fix this on 0.5.

**Comment by timholy** [comment]
This seems too outdated to be useful.
