### ISSUE TITLE
Order of using statements can break things on julia 0.6

### ISSUE THREAD

**Issue by davidanthoff** [JuliaPackaging/Requires.jl#36]
You need the packages ``IterableTables`` and ``CSV`` to repo this. Checkout the branch ``requires-repo`` in ``IterableTables``.

Then things work if I first load ``CSV`` and then ``IterableTables`` (I removed some deprecation warning output for clarity):
````julia
julia> using CSV, IterableTables
DataStreams integration was loaded.
````
But when I switch the order to load ``IterableTables`` first, things don't work anymore:
````julia
julia> using IterableTables, CSV
julia>
````
I.e. in this case the code in the ``@require`` block never runs.

The structure here is that ``CSV`` has a ``using DataStreams`` statement [here](https://github.com/JuliaData/CSV.jl/blob/master/src/CSV.jl#L4), so things are a little more indirect, but at least on julia 0.5 this works without a problem.

@vchuravy @MikeInnes

**Comment by vchuravy** [comment]
This is an issue with how upstream Julia handles deserialisation of precompilation cache files...  (and that changed between 0.5 and 0.6)
Requires gets loaded to late to overwrite the `Base.require` method used for deserialization and so it never sees packages that are coming from the cache.

**Comment by davidanthoff** [comment]
Hm, so essentially this means we can't get things to work properly on julia 0.6?

Is a workaround that my ``@require`` statement has to be on ``CSV`` (and ``Feather`` etc.) instead of the upstream package ``DataStreams``?

**Comment by davidanthoff** [comment]
Ok, I think I have a workaround in davidanthoff/IterableTables.jl#28. It certainly is not elegant, but might do the trick for now.

**Comment by vchuravy** [comment]
If you can I would hold off on merging this for now. I am hopeful that I can get this fixed upstream, but no promises.

**Comment by davidanthoff** [comment]
Yes, I'm following that issue. Thanks so much for trying to sort this out, much appreciated!!

**Comment by timholy** [comment]
Is this still relevant?

**Comment by davidanthoff** [comment]
Probably not :)
