### ISSUE TITLE
Demo code works without import JSON

### ISSUE THREAD

**Issue by musm** [JuliaPackaging/Requires.jl#60]
I'm testing this package and the stated behavior in the README is not valid.  For example following the README
```julia
module Reqs

using Requires

function __init__()
    @require JSON="682c06a0-de6a-54ab-a142-c8b1cf79cde6" @eval using Colors
    @require JSON="682c06a0-de6a-54ab-a142-c8b1cf79cde6" f() = 2
end

end

```

and then
```julia
julia> using Main.Reqs

julia> Reqs.f()   # works even without importing JSON
julia>Reqs.Colors.RGB(1,0,0) # also works without importing JSON
```

**Comment by DilumAluthge** [comment]
@musm I am not able to reproduce this bug. What version of Requires are you using, and what version of Julia?

I ran your code snippets (with Julia v1.1.0 and Requires v0.5.2) and the behavior was as expected, i.e. `Reqs.f()` and `Reqs.Colors.RGB(1,0,0)` did not work before I ran `import JSON`, and did work after I ran `import JSON`.

**Comment by timholy** [comment]
@musm, I'm guessing you're using Juno.

```julia
julia> pkgnames = (id->id.name).(keys(Base.loaded_modules));

julia> "JSON" ∈ pkgnames
true
```

Could you please change the example to use a package that Juno doesn't load?

**Comment by timholy** [comment]
Guessing this was due to Juno.
