### ISSUE TITLE
unit tests (documentation request)

### ISSUE THREAD

**Issue by pyramids** [JuliaPackaging/Requires.jl#62]
I fail at writing unit tests for methods overwritten by `@require`. There are two problems I'm grappling with:

1. `julia` complains if I don't add the optional dependency to the package, possibly causing the next issue.
2. Whilst a test I want to write works in the REPL if I start with `using` my package and the optional dependency, it fails to replace the method in question when executed via `] test` from the file `test/runtests.jl`.

Is there a chance that some documentation (or, better yet, a brief example) could be added to the documentation? Thanks alot!

**Comment by timholy** [comment]
A copy/pastable example would surely make this easier to address

**Comment by pyramids** [comment]
Thank you for the speedy reply. I made a minimum example project as follows.

src/Demo.jl:
```julia
module Demo
using Requires
function __init__()
    @require DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0" Base.show(io::IO, mime::MIME"text/html", df::DataFrame) = print(io, "Success")
end # __init__
end # module
```

test/runtests.jl:
```julia
using Test
using DataFrames
@test begin
    io = IOBuffer()
    show(io, "text/html", DataFrame())
    return String(take!(io))
end == "success"
```

This works if I add `DataFrames` and then `Requires` as dependencies with `] add`. In particular, `] test` reports that the test passes.

Then I try removing the dependency on `DataFrames`. Now the test fails saying I am missing that package. Next I add it as an extra (test-only) dependency.

Project.toml then ends in
```
[deps]
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[extras]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
```

But the error message about `DataFrames` being a missing package persists. Doesn't it defeat `Requires`' purpose if I must add dependency packages into my project if I want to have unit tests?

**Comment by shipengcheng1230** [comment]
> test = ["Test"]

Perhaps add `DataFrames` in addition in this line?

**Comment by timholy** [comment]
@shipengcheng1230 has the right answer; this is a package-management issue, not a Requires issue.
