### ISSUE TITLE
current master and precompilation

### ISSUE THREAD

**Issue by jverzani** [JuliaPackaging/Requires.jl#9]
Trying to get the precompilation of a package that depends on `Requires`. I'm using the latest master and  get this error when trying to precompile:

```
julia> using Requires
INFO: Precompiling module Requires...
WARNING: eval from module Base to Requires:    
Expr(:block, Expr(:line, 16, :/Users/verzani/.julia/v0.4/Requires/src/require.jl)::Any, Expr(:toplevel, Expr(:import, :MacroTools)::Any, Expr(:import, :Requires)::Any)::Any)::Any
  ** incremental compilation may be broken for this module **

WARNING: eval from module Base to Requires:    
Expr(:block, Expr(:line, 20, :/Users/verzani/.julia/v0.4/Requires/src/require.jl)::Any, Expr(:macrocall, Expr(:., :MacroTools, :@hook)::Any, Expr(:function, Expr(:call, :require, Expr(:::, :s, :Symbol)::Any)::Any, Expr(:block, Expr(:line, 21, :/Users/verzani/.julia/v0.4/Requires/src/require.jl)::Any, Expr(:call, :super, :s)::Any, # line 22, Expr(:call, Expr(:., :Requires, :loadmod)::Any, Expr(:call, :string, :s)::Any)::Any)::Any)::Any)::Any)::Any
  ** incremental compilation may be broken for this module **
```

I have no idea what to make of this :( I don't think the issue is with `MacroTools`, that seems to precompile and load just fine.

**Comment by one-more-minute** [comment]
To get this working, at a minimum, you want [these lines](https://github.com/one-more-minute/Requires.jl/blob/fc900c32a876a9367ce30c0dc53577d291e95b16/src/require.jl#L15-L23) to happen as part of the Require's `__init__()`. That should fix the error you're seeing, but given the level of hackiness going on in Requires will probably be other things blocking it from working with precompilation.

**Comment by jverzani** [comment]
Thanks. Let me try that and if it works, will get back with a PR.

On Tue, Aug 11, 2015 at 9:55 AM, Mike J Innes <notifications@github.com>
wrote:

> To get this working, at a minimum, you want these lines
> <https://github.com/one-more-minute/Requires.jl/blob/fc900c32a876a9367ce30c0dc53577d291e95b16/src/require.jl#L15-L23>
> to happen as part of the Require's __init__(). That should fix the error
> you're seeing, but given the level of hackiness going on in Requires will
> probably be other things blocking it from working with precompilation.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/one-more-minute/Requires.jl/issues/9#issuecomment-129883522>
> .
>



-- 
John Verzani
Chair, Department of Mathematics
College of Staten Island, CUNY
verzani@math.csi.cuny.edu

**Comment by jverzani** [comment]
Sorry, I struck out. I'll have to wait for you to fix.

On Tue, Aug 11, 2015 at 10:02 AM, John Verzani <jverzani@gmail.com> wrote:

> Thanks. Let me try that and if it works, will get back with a PR.
>
> On Tue, Aug 11, 2015 at 9:55 AM, Mike J Innes <notifications@github.com>
> wrote:
>
>> To get this working, at a minimum, you want these lines
>> <https://github.com/one-more-minute/Requires.jl/blob/fc900c32a876a9367ce30c0dc53577d291e95b16/src/require.jl#L15-L23>
>> to happen as part of the Require's __init__(). That should fix the error
>> you're seeing, but given the level of hackiness going on in Requires will
>> probably be other things blocking it from working with precompilation.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/one-more-minute/Requires.jl/issues/9#issuecomment-129883522>
>> .
>>
>
>
>
> --
> John Verzani
> Chair, Department of Mathematics
> College of Staten Island, CUNY
> verzani@math.csi.cuny.edu
>



-- 
John Verzani
Chair, Department of Mathematics
College of Staten Island, CUNY
verzani@math.csi.cuny.edu

**Comment by timholy** [comment]
A lot has changed about how this package works, and this no longer seems to be an issue.
