### ISSUE TITLE
Migrate to travis-ci.com

### ISSUE THREAD

**Issue by ranocha** [JuliaPackaging/Requires.jl#93]
I noticed that this repo still uses travic-ci.org, at least based on the badge in the README. travis-ci.org will be shut down at the end of the year, cf. https://mailchi.mp/3d439eeb1098/travis-ciorg-is-moving-to-travis-cicom. Hence, everything should be migrated to travis-ci.com.

The Travis badge in the README is currently broken since it points to `MikeInnes/Requires.jl` instead of `JuliaPackaging/Requires.jl`.

**Comment by fingolfin** [comment]
Or given https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing directly migrate to GitHub Actions or something else that's not super limited for OSS these days...

**Comment by timholy** [comment]
Superseded by #98, will be fixed by #106
