### ISSUE TITLE
Requires 1.1.0 broke Revise

### ISSUE THREAD

**Issue by timholy** [JuliaPackaging/Requires.jl#94]
xref #85, posting as an issue so it doesn't get forgotten.

I spend too much time maintaining Revise, and in an attempt to shed some of the burden I'm assigning this bug to "not me." Whoever addresses it, note that Revise is getting a fake upper bound that will block testing of anything higher than Requires 1.0.x (https://github.com/timholy/Revise.jl/pull/551), so to test fixes you'll need to relax that locally.

**Comment by c42f** [comment]
It appears this may be due to the use of `Base.include(mod, filename)` rather than bare `include(filename)` at https://github.com/JuliaPackaging/Requires.jl/blob/705e5fa8d3320c7600e25b4281f419475620066f/src/Requires.jl#L22

Would that make sense?

**Comment by c42f** [comment]
> It appears this may be due to the use of `Base.include(mod, filename)` rather than bare `include(filename)`

Actually no, ignore that. It appears I've gotten myself confused.

**Comment by c42f** [comment]
So it turns out I was close. It seems that `Revise` needs a literal string `include("file.jl")` rather than `file="file.jl"; include(file)` to be able to track includes. But we're using a variable instead in the code emitted from `@include`.
